// Copyright (c) 2023 - 2026 Skip
// Licensed under the GNU Affero General Public License v3.0
// SPDX-License-Identifier: AGPL-3.0-only

import Foundation
import ArgumentParser
import TSCBasic
import SkipSyntax

/// The hardwired maximum of snippet generation
fileprivate let codebaseThresholdSize = 1_000

struct SnippetCommand: SnippetOptionsCommand, StreamingCommand {
    static let configuration = CommandConfiguration(commandName: "snippet", abstract: "Transpile a snippet of Swift to Kotlin", shouldDisplay: false)

    @OptionGroup(title: "Snippet Options")
    var snippetOptions: SnippetOptions

    @OptionGroup(title: "Output Options")
    var outputOptions: OutputOptions

    @Option(name: [.customLong("codebase")], help: ArgumentHelp("Path to codebase to reference", valueName: "skipcode.json"))
    var codebases: [String] = [] // --module name:path

    @Argument(help: ArgumentHelp("List of files to process"))
    var files: [String]

    struct Output : MessageEncodable {
        let kotlin: String?
        let version: String = skipVersion
        let messages: [Message]?
        let duration: TimeInterval?

        /// The raw description is just the Kotlin, with error messages preceeding it
        func message(term: Term) -> String? {
            var comments = "// Generated by skip.tools \(version)\n"

            for msg in messages ?? [] {
                // TODO: when in the console, output colors for the ANSI messages
                comments += msg.formattedMessage.split(separator: "\n").map({ "//" + $0 }).joined(separator: "\n") + "\n"
            }

            return comments + (kotlin ?? "")
        }
    }

    func performCommand(with out: MessageQueue) async throws {
        let totalSize = try files.compactMap({ try URL(fileURLWithPath: $0).resourceValues(forKeys: [.fileSizeKey]).fileSize }).reduce(0, +)

        // snippets are hardwired to not exceed the default codebase threshold size
        if totalSize > codebaseThresholdSize {
            await out.yield(Output(kotlin: nil, messages: [Message(kind: .error, message: "Snippet too large \(totalSize.byteCount)")], duration: 0))
            await out.finish()
            return
        }

        let sourceFiles = files.map(Source.FilePath.init(path:))
        try await self.transpileSnippet(fs: localFileSystem, sourceFiles: sourceFiles, with: out)
    }

    private func transpileSnippet(fs: FileSystem, sourceFiles: Array<Source.FilePath>, with out: MessageQueue) async throws {

        let codebaseInfo = CodebaseInfo()

        for codebasePath in codebases {
            // load each of the specified codebases
            let cbdata = try Data(contentsOf: URL(fileURLWithPath: codebasePath))
            let decoder = JSONDecoder()
            let export = try decoder.decode(CodebaseInfo.ModuleExport.self, from: cbdata)
            codebaseInfo.dependentModules.append(export)
        }

        let transpiler = Transpiler(packageName: nil, transpileFiles: sourceFiles, codebaseInfo: codebaseInfo, transformers: builtinKotlinTransformers())
        try await transpiler.transpile { transpilation in
            // note that transpilation messages are included as part of the output itself, rather than being logged as a message
            let msgs = transpilation.messages
            let output = Output(kotlin: transpilation.output.content, messages: msgs, duration: transpilation.duration)
            await out.yield(output)
        }
        await out.finish()
    }
}

